version: '3'

services:
  etcd:
    image: soyking/etcd-goreman:3.2.7
  e3w:
    image: soyking/e3w:latest
    volumes:
      - ./conf/config.default.ini:/app/conf/config.default.ini
    command: sh -c "sleep 10 && ./e3w"
    ports:
      - "8080:8080"
    depends_on:
      - etcd
